name: Update Token

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Create and run Python script
      run: |
        cat > update_token.py << 'EOF'
        import requests
        import base64
        import json
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

        def update_token():
            # API bilgileri
            api_url = "https://core-api.kablowebtv.com/api/channels"
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                "Referer": "https://tvheryerde.com", 
                "Origin": "https://tvheryerde.com",
                "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbnYiOiJMSVZFIiwiaXBiIjoiMCIsImNnZCI6IjA5M2Q3MjBhLTUwMmMtNDFlZC1hODBmLTJiODE2OTg0ZmI5NSIsImNzaCI6IlRSS1NUIiwiZGN0IjoiRTFDNjQiLCJkaSI6Ijg5MTlmNjYwLTBhZGUtNGYwMS1hMTVlLTc2MDZjNjI4ZTc5MyIsInNnZCI6IjM5MTY0ZjIwLTZlZjUtNDRlZS04ZjAyLWEzODRjOTg1ZTY5MyIsInNwZ2QiOiI5ZjJlYWE1NC01NDM2LTQ0ZTgtYTkyNy00MzQ2NjlkMTU1MWEiLCJpY2giOiIwIiwiaWRtIjoiMCIsImlhIjoiOjpmZmZmOjEwLjAuMC41IiwiYXB2IjoiMS4wLjAiLCJhYm4iOiIxMDAwIiwibmJmIjoxNzQzNDY1MzY5LCJleHAiOjE3NDM0NjU0MjksImlhdCI6MTc0MzQ2NTM2OX0.YWdVfOL5hEZTrd4f4qkmPCPmUUlaiG7I2REW5H0p6Gw",
                "Accept": "application/json, text/plain, */*",
            }

            try:
                # API'den veri al
                response = requests.get(api_url, headers=headers, timeout=30, verify=False)
                
                if response.status_code != 200:
                    raise Exception(f"API HTTP {response.status_code}")
                
                data = response.json()
                
                # GÜVENLİ veri kontrolü
                if not data or not isinstance(data, dict):
                    raise Exception("Geçersiz API yanıtı")
                
                if 'Data' not in data or not isinstance(data['Data'], dict):
                    raise Exception("Data bulunamadı")
                
                if 'AllChannels' not in data['Data'] or not isinstance(data['Data']['AllChannels'], list):
                    raise Exception("AllChannels bulunamadı")
                
                # ATV kanalını bul - GÜVENLİ şekilde
                atv_channel = None
                for channel in data['Data']['AllChannels']:
                    if not isinstance(channel, dict):
                        continue
                    
                    stream_data = channel.get('StreamData')
                    if not isinstance(stream_data, dict):
                        continue
                    
                    stream_url = stream_data.get('HlsStreamUrl', '')
                    if isinstance(stream_url, str) and 'atv_stream' in stream_url:
                        atv_channel = channel
                        break
                
                if not atv_channel:
                    raise Exception("ATV kanalı bulunamadı")
                
                stream_url = atv_channel['StreamData']['HlsStreamUrl']
                prefix = "https://ottcdn.kablowebtv.net/live_turksat_sub3/atv_stream/index.m3u8?wmsAuthSign="
                
                if not stream_url.startswith(prefix):
                    raise Exception("URL formatı hatalı")
                
                # Token'i al
                token = stream_url[len(prefix):]
                
                # Token'i decode et
                decoded_token = base64.b64decode(token).decode('utf-7')
                
                # Parametreleri parse et
                params = {}
                for pair in decoded_token.split('&'):
                    if '=' in pair:
                        key, value = pair.split('=', 1)
                        params[key] = value
                
                # SADECE IP ADRESİNİ DEĞİŞTİR
                params['client_ip'] = '176.88.30.202'
                
                # Yeni token string'ini OLDUĞU GİBİ oluştur
                new_token_string = f"server_time={params['server_time']}&hash_value={params['hash_value']}&validminutes={params['validminutes']}&id={params['id']}&client_ip={params['client_ip']}&checkip={params['checkip']}"
                
                # Base64 encode et
                new_token = base64.b64encode(new_token_string.encode('utf-7')).decode('utf-7')
                
                # Dosyaya yaz
                with open('token.txt', 'w') as f:
                    f.write(new_token)
                
                return new_token
                
            except Exception as e:
                raise Exception(f"API hatası: {str(e)}")

        try:
            token = update_token()
            print("✓ Token başarıyla güncellendi")
            
            # Kontrol
            decoded = base64.b64decode(token).decode('utf-7')
            print("Decode edilmiş token:", decoded)
            
        except Exception as e:
            print(f"✗ Hata: {e}")
            exit(1)
        EOF

        python update_token.py

    - name: Debug - Show token file
      run: |
        echo "Token:"
        cat token.txt
        echo -e "\nDecoded:"
        base64 -d token.txt

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add token.txt
        git diff --staged --quiet || git commit -m "Update token - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
